import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1200, height: 1600 } });
const urls = [];
p.on('response', r => { const u = r.url(); if (/json|api|csv|stax/i.test(u) && !/\.(js|css|png|svg|woff)/.test(u)) urls.push(r.status() + ' ' + u); });
await p.goto('https://www.schwab.com/investment-research/stax/view-schwab-trading-activity-index', { timeout: 60000 });
await p.waitForTimeout(8000);
console.log('STAX XHR', JSON.stringify(urls.slice(0, 40), null, 1));
const t = await p.evaluate(() => document.body.innerText);
const i = t.indexOf('STAX'); console.log('STAX TEXT', t.slice(i, i + 2500));
await p.screenshot({ path: 'probe/stax.png' });
await b.close();
